Add min compile check job

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,8 +5,32 @@ on: [push, pull_request, workflow_dispatch]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  Linux:
+  # Check to make sure we can still compile on 1.17 (for customers on older go toolchains)
+  Linux-Compile117:
+        # The type of runner that the job will run on
+        runs-on: ubuntu-20.04
+        # Steps represent a sequence of tasks that will be executed as part of the job
+        steps:
+          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+          - uses: actions/checkout@v2
+          - name: Setup Go environment
+            uses: actions/setup-go@v2.1.3
+            with:
+              go-version: '1.17'
+          - name: Compiles
+            run: go build ./...
+    
+          - name: Runs go fmt
+            if: ${{ success() }}
+            run: |
+              OUTPUT=$(go fmt ./... 2>&1)
+              if [ ! -z "$OUTPUT" ]; then
+                echo "go fmt failed on the following files:"
+                echo "$OUTPUT"
+                exit 1
+              fi
+  # Test functionality on latest (stable) go version
+  Linux-Latest:
     # The type of runner that the job will run on
     runs-on: ubuntu-20.04
 
